import type { Card } from '@/types/game'
import { BASE_PATH } from './basePath'

export function getLocalCardPath(card: Card): string {
  const filename = card.img.split('/').pop() || ''
  return `${BASE_PATH}/cards/${filename}`
}

/**
 * Low-res thumbnail variant (480px wide JPEG @ q70) for every render site
 * smaller than ~234px wide. Only the gallery Spotlight (~656px tall hero)
 * needs the full-res 700×978 source — that's the one site that should keep
 * calling getLocalCardPath. Thumbnails live under public/cards/thumbs/ and
 * are generated by scripts/make-thumbs.mjs.
 */
export function getLocalCardThumbPath(card: Card): string {
  const filename = card.img.split('/').pop() || ''
  return `${BASE_PATH}/cards/thumbs/${filename}`
}

export function getCardBackPath(): string {
  return `${BASE_PATH}/cards/_back.jpg`
}

export function getMatImagePath(dim = true): string {
  return `${BASE_PATH}/mat/${dim ? 'zutomayo_field01_dim.jpg' : 'zutomayo_field01.jpg'}`
}
